#
# ファイル/フォルダ構成の記述
#
Regex         : "Lot(?<lot>[0-9]{4})\\\\wafer(?<wf>[0-9]{2})\\\\N(?<chip>[0-9]{2})" #Mono\\
searchPattern : "N*"
ChipNote      : "N[0-9]{2}_[a-zA-Z0-9]+_(?<note>[a-zA-Z0-9]+)$"
Condition     :
  Dark     : Dark_30FPS
  Dark60   : Dark
  L10      : L10_30fps
  L10SH    : L10_SH_30FPS
  L50      : L50_30fps
  L90      : L90_30fps
  L300     : L300_30fps
  Dark4clk : DARK_TG4RCK_30fps
  VNtest1 : LSB300_60FPS
  VNtest2 : LSB600_60FPS
  VNtest3 : LSB900_60FPS
  VNtest4 : LSB1200_60FPS
  VNtest5 : LSB1500_60FPS
  VNtest6 : LSB1800_60FPS
  VNtest7 : LSB2100_60FPS
  VNtest8 : LSB3000_60FPS
  VNtest9 : LSB4200_60FPS
Picture :
  Ave         : 
    Name : ave.bin
    Type : Single
  Dev         : 
    Name : dev.bin
    Type : Single
  Single      : 
    Name : sgl.bin
    Type : Int32
  Ave-hob     : 
    Name : ave_hob.bin
    Type : Single
  Dev-hob     : 
    Name : dev_hob.bin
    Type : Single
  Single-hob  : 
    Name : sgl_hob.bin
    Type : Int32
Colors :
  M :
    x      : 0
    y      : 0
    step_x : 1
    step_y : 1
  M1 :
    x      : 0
    y      : 0
    step_x : 1 
    step_y : 4
  M2 :
    x      : 0
    y      : 1
    step_x : 1
    step_y : 4
  M3 :
    x      : 0
    y      : 2
    step_x : 1
    step_y : 1
  M4 :
    x      : 0
    y      : 3
    step_x : 1
    step_y : 4
  B :
    x      : 0
    y      : 0
    step_x : 2
    step_y : 2
  Gb  :
    x      : 1
    y      : 0
    step_x : 2
    step_y : 2
  Gr  :
    x      : 0
    y      : 1
    step_x : 2
    step_y : 2
  R :
    x      : 1
    y      : 1
    step_x : 2
    step_y : 2
  B1 :
    x      : 0
    y      : 0
    step_x : 2
    step_y : 4
  Gb1  :
    x      : 1
    y      : 0
    step_x : 2
    step_y : 4
  Gr1  :
    x      : 0
    y      : 1
    step_x : 2
    step_y : 4
  R1 :
    x      : 1
    y      : 1
    step_x : 2
    step_y : 4
  B2 :
    x      : 0
    y      : 2
    step_x : 2
    step_y : 4
  Gb2  :
    x      : 1
    y      : 2
    step_x : 2
    step_y : 4
  Gr2  :
    x      : 0
    y      : 3
    step_x : 2
    step_y : 4
  R2 :
    x      : 1
    y      : 3
    step_x : 2
    step_y : 4
Maps :
  Full : 
    Left   : 0 
    Top    : 0
    Width  : 2256
    Height : 1178
  Normal : 
    Left   : 149 
    Top    : 39
    Width  : 1956
    Height : 1116
  Effective : 
    Left   : 154 
    Top    : 43
    Width  : 1948
    Height : 1108
  Active : 
    Left   : 160 
    Top    : 49
    Width  : 1936
    Height : 1096
  HOB-L : 
    Left   : 12 
    Top    : 49
    Width  : 128
    Height : 1096
  HOB-R : 
    Left   : 2116 
    Top    : 49
    Width  : 128
    Height : 1096